### ISSUE TITLE
Error while running multiple functions in class with only one client

### ISSUE THREAD

**Issue by Jey0707** [CheshireCaat/bas-remote-python#2]
I'm sorry for stressing you out...
I'm having this error when I try to execute this code with only one client as you suggested. I don't know if I'm missing something with asyncio, in this case sorry for brothering you..

This is my code: https://pastebin.com/pf46tSK9

**Comment by CheshireCaat** [comment]
This error is not related to this package. You're using `asyncio.run` incorrectly - just use the `asyncio.run` once. Also check `asyncio` docs - https://docs.python.org/3/library/asyncio-task.html.
