### ISSUE TITLE
The "Quick example" doesn't work for me

### ISSUE THREAD

**Issue by Jaden024** [CheshireCaat/bas-remote-python#7]
I believe that the BAS engine was successfuly installed, I even tried to unzip it but it didn't help. 
 
![image](https://github.com/user-attachments/assets/e284f767-8d8f-4645-bdbe-381c29f47de1)

**Comment by CheshireCaat** [comment]
Greetings! Please follow these steps:

1. Delete the engine folder completely (data folder).
2. Install version 1.6 of this library.
3. Try running the code again.

If this does not help, try setting your own startup timeout (more than the default one):

```python
await script_client.start(300)
```

If this does not help, attach the entire console output and the full test code.

**Comment by Jaden024** [comment]
Hello again, didn't expect such a quick response :) Installing the version 1.6 did resolve the issue. Thanks for help and for creating BAS.
